name: Terraform AWS example workflow

on:
  push:
    branches: [ "main" ]

env:
  TF_VERSION: "1.4.0"

permissions:
  id-token: write
  contents: read

jobs:
  TerraformDeployment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, stage]
        aws_account: ["arn:aws:iam::666562444707:role/new_oidc_github", "arn:aws:iam::666562444707:role/github-oidc-stage"]
    
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials for each environment
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ matrix.aws_account }}
          audience: sts.amazonaws.com
          aws-region:  ${{ env.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        working-directory: terraform/${{ matrix.environment }}
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform/${{ matrix.environment }}
        run: terraform validate
      
      - name: Terraform Plan
        working-directory: terraform/${{ matrix.environment }}
        run: terraform plan -var-file=${{ matrix.environment }}/terraform.tfvars -out=tfplan

      - name: Terraform Apply
        working-directory: terraform/${{ matrix.environment }}
        run: terraform apply -auto-approve tfplan