# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow Creates static website using Terraform and AWS S3
name: Terraform AWS example workflow
on:
  push:
    branches: [ "main" ]
env:
  BUCKET_NAME: "githubsample-645373"
  AWS_REGION: "ap-south-1"
  TF_VERSION: "1.4.0"
# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  S3TerraformDeployment:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::666562444707:role/new_oidc_github
          audience: sts.amazonaws.com
          aws-region: ${{ env.AWS_REGION }}

      # Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
      
      # Terraform init
      - name: Terraform Init
        run: terraform init

      # Terraform validate
      - name: Terraform Validate
        run: terraform validate

      # Terraform plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Terraform apply
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan