name: AWS Terraform Workflow2

on:
 workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (apply or destroy)'
        required: true
        type: choice
        options:
        - apply
        - destroy
env:
  BUCKET_NAME: "githubsample-645373"
  AWS_REGION: "ap-south-1"

permissions:
  id-token: write
  contents: read

jobs:
  terraform-init:
    name: Terraform Init Stage
    runs-on: ubuntu-latest

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v2
       

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::666562444707:role/new_oidc_github
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

